In [48]:
import numpy as np

# Exercice 1 :

- Créer une fonction diviseur(n) qui retourne les diviseurs positifs d'un entier naturel n.

In [12]:
def diviseur(n: int) -> list:
    diviseurs = []
    for i in range(1, n+1):
        if n % i == 0:
            diviseurs += [i]
    return diviseurs

In [13]:
diviseur(30)

[1, 2, 3, 5, 6, 10, 15, 30]

- Deux entiers naturels a et b sont amis ssi : "(somme des diviseurs positifs de a) ×b" est égal à "(somme des diviseurs positifs de b) ×a".

Créer une fonction amis(a,b) retournant True ssi deux entiers sont amis, False sinon.

In [68]:
def amis(a: int, b: int) -> bool:

    somme_diviseurs_a = 0
    for i in range(1, a):
        if a % i == 0:
            somme_diviseurs_a += i
    
    somme_diviseurs_b = 0
    for i in range(1, b):
        if b % i == 0:
            somme_diviseurs_b += i

    if (somme_diviseurs_a * b) == (somme_diviseurs_b * a):
        booleen = True
    else:
        booleen = False

    return booleen

In [69]:
print(amis(30,140),amis(30,141))

True False


# Exercice 2 :

- Créer une fonction `decalage(x) qui associe à une lettre de l'alphabet x la lettre située juste avant dans l'alphabet.

Par convention, on fera decalage(A) = Z.

In [66]:
def decalage(x: str) -> str:
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    
    emplacement = alphabet.index(x)-1
    
    if emplacement == -1:
        emplacement = 25
    
    return alphabet[emplacement]

In [67]:
print(decalage("D"), decalage("Z"), decalage("A"))

C Y Z


- Créer une fonction insertA(mot) qui associe à un mot une chaîne de caractère construite de la façon suivante : première lettre du mot, puis "A", puis deuxième lettre du mot, puis "A", etc.

In [45]:
def insertA(mot: str) -> str:
    resultat = ""
    for i in range(len(mot)):
        resultat += mot[i] + "A"
    return resultat

In [46]:
insertA("POIRE")

'PAOAIARAEA'

# Exercice 3 :

- Construire une fonction diagcal(A,booléen) qui, pour une matrice carrée A, retourne la somme des coefficients situés sur la diagonale descendante si booléen = True, et la multiplication de ces coefficients si booléen = False.

In [49]:
A = np.array([[2,4,3,12],[1,9,15,-3],[23,6,7,2],[2,4,5,3]])
print(A)

[[ 2  4  3 12]
 [ 1  9 15 -3]
 [23  6  7  2]
 [ 2  4  5  3]]


In [60]:
def diagcal(A: list, booleen: bool) -> tuple:
    
    if booleen == True:
        nb = -1
        calcul = 0
        for i in range(len(A)):
            nb += 1
            calcul += A[i][nb]
    
    elif booleen == False:
        nb = -1
        calcul = 1
        for i in range(len(A)):
            nb += 1
            calcul *= A[i][nb]
    
    return calcul

In [61]:
print(diagcal(A,True), diagcal(A,False))

21 378


# Exercice 4 :

- Un nombre semipremier est le produit de deux nombres premiers (non nécessairement distincts). Créer une fonction semiPrem(k) qui affiche les nombres semipremiers inférieurs à k.

In [125]:
def semiPrem(k):
    
    # Trouver les nombres premiers
    primes = [2]
    for i in range(3, k):
        booleen = True
        for j in range(2, i):
            if i % j == 0:
                booleen = False
        if booleen == True:
            primes += [i]
    
    # Trouver les nombres semipremiers parmi les nombres premiers
    liste = []
    for i in range(len(primes)):
        for j in range(i, len(primes)):
            if primes[i] * primes[j] < k:
                liste += [primes[i] * primes[j]]
    
    return sorted(liste)

In [126]:
semiPrem(50)

[4, 6, 9, 10, 14, 15, 21, 22, 25, 26, 33, 34, 35, 38, 39, 46, 49]