# Matrices

In [1]:
import numpy as np

## 1. Ecriture matricielle

### 1.1 Création de matrices

In [2]:
M = np.array([[2,3,4],[-1,4,5],[-5,6,7],[1,0,2]])
M

array([[ 2,  3,  4],
       [-1,  4,  5],
       [-5,  6,  7],
       [ 1,  0,  2]])

In [3]:
#nombre de coefficients de M
np.size(M)

12

In [4]:
#nombre de lignes de M
np.shape(M)[0]

4

In [5]:
#nombre de colonnes de M
np.shape(M)[1]

3

### 1.2 Extraction de coefficients

In [6]:
M[0,1]

3

In [7]:
M[3,2]

2

In [8]:
M[0,1:3]

array([3, 4])

In [9]:
M[0,0:3]

array([2, 3, 4])

In [10]:
M[0,:]

array([2, 3, 4])

In [11]:
M[1,:]

array([-1,  4,  5])

In [12]:
# affectation à une ligne
M[2,:] = [2,4,6]
M[1,:] = 2 * M[2,:]
M[0,:] = 0
M

array([[ 0,  0,  0],
       [ 4,  8, 12],
       [ 2,  4,  6],
       [ 1,  0,  2]])

In [13]:
M = np.array([[2,3,4],[-1,4,5],[-5,6,7],[1,0,2]])
N = np.copy(M)
N[0,0] = 88
M

array([[ 2,  3,  4],
       [-1,  4,  5],
       [-5,  6,  7],
       [ 1,  0,  2]])

In [14]:
N

array([[88,  3,  4],
       [-1,  4,  5],
       [-5,  6,  7],
       [ 1,  0,  2]])

### 1.3 Fonctions np.zeros(), np.eye(), np.ones()

In [15]:
# que font les fonctions suivantes ?
print(np.zeros((3,5))) # matrice de 0 de largeur 3 et longueur 5
print("\n")
print(np.eye(3)) # matrice carré de 0 de longueur 3 avec diagonal de 1
print("\n")
print(np.ones((3,5))) # matrice de 1 de largeur 3 et longueur 5

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2. Multiplication matricielle

In [16]:
M = np.array([[2,3,4],[-1,4,5],[-5,6,7],[1,0,2]])
P = np.array([[2,3,3,5],[-1,4,5,6],[-5,2,7,8],[1,0,-2,9]])
np.dot(P,M)

array([[ -9,  36,  54],
       [-25,  43,  63],
       [-39,  35,  55],
       [ 21,  -9,   8]])

np.dot(P,M) permet de multiplier deux matrices avec le meme nombre de colonne pour P et avec le meme nombre de ligne pour M.

### 2.1 Exercice : matrice Identité

In [17]:
P = np.array([[2,3,3,5],[-1,4,5,6],[-5,2,7,8],[1,0,-2,9]])
I = np.eye(4)
print(np.dot(P,I))
print("\n")
print(np.dot(I,P))

[[ 2.  3.  3.  5.]
 [-1.  4.  5.  6.]
 [-5.  2.  7.  8.]
 [ 1.  0. -2.  9.]]


[[ 2.  3.  3.  5.]
 [-1.  4.  5.  6.]
 [-5.  2.  7.  8.]
 [ 1.  0. -2.  9.]]


Ici, les deux matrices sont carrés donc le nombre de colonne de P et le nombre de ligne de I sont identiques.

### 2.2 Exercice : puissance de matrices

In [18]:
def puissance(A: list, p: int) -> list:
    B = np.copy(A)
    for i in range(p-1):
        B = np.dot(A, B)
    return B

In [19]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
puissance(A,5)

array([[121824, 149688, 177552],
       [275886, 338985, 402084],
       [429948, 528282, 626616]])

## 3. Exercices d'applications

In [21]:
def diagInv(n: int) -> list:
    A = np.zeros((n,n))
    indice = len(A)-1
    for i in range(len(A)):
        A[i, indice] = 1
        indice -= 1
    return A

In [22]:
diagInv(4)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [23]:
def negatifzero(M: list) -> list:
    N = np.copy(M)
    for i in range(len(N)):
        for j in range(len(N[i])):
            if N[i, j] < 0:
                N[i, j] = 0
    return N

In [24]:
P

array([[ 2,  3,  3,  5],
       [-1,  4,  5,  6],
       [-5,  2,  7,  8],
       [ 1,  0, -2,  9]])

In [25]:
negatifzero(P)

array([[2, 3, 3, 5],
       [0, 4, 5, 6],
       [0, 2, 7, 8],
       [1, 0, 0, 9]])

In [2]:
def matriceliste(v: list, n: int) -> list:
    w = np.zeros((n,len(v)))
    for i in range(len(v)):
        w[0, i] = v[i]
    for j in range(1, len(w)):
        for k in range(len(w[j])):
            w[j, k] = w[j-1, k] * w[0, k]
    return w

In [3]:
print(matriceliste([2,3,4], 4))
print(matriceliste([2,3,4], 5))

[[  2.   3.   4.]
 [  4.   9.  16.]
 [  8.  27.  64.]
 [ 16.  81. 256.]]
[[   2.    3.    4.]
 [   4.    9.   16.]
 [   8.   27.   64.]
 [  16.   81.  256.]
 [  32.  243. 1024.]]


In [28]:
def plusligneprecedente(M: list) -> list:
    N = np.copy(M)
    copyN = np.copy(N[-1])
    for i in range(len(N)-1, 0, -1):
        N[i] += N[i-1]
    N[0] += copyN
    return N

In [29]:
M

array([[ 2,  3,  4],
       [-1,  4,  5],
       [-5,  6,  7],
       [ 1,  0,  2]])

In [30]:
plusligneprecedente(M)

array([[ 3,  3,  6],
       [ 1,  7,  9],
       [-6, 10, 12],
       [-4,  6,  9]])

## 4. Bonus

In [6]:
def produit(A: list, B: list) -> list:
    if np.shape(A)[1] == np.shape(B)[0]:
        res = np.dot(A, B)
    else:
        res = A*B
    return res

In [7]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[7,8,9],[1,2,3]])
Y = np.array([[0,1,3,0],[8,5,0,6],[0,0,1,1]])
Z = np.array([[0,1],[0,0],[3,3],[9,5]])

print(produit(W, X))
print("\n")
print(produit(Y, Z))

[[ 7 16 27]
 [ 4 10 18]]


[[ 9  9]
 [54 38]
 [12  8]]


[Lien test Y et Z](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0jboqZ51ccbQ0D4-Ln92vGOxulFd2nVoGAUmRIVk3h4uxOUV0CPwawWMZnQAjUq4zYSI&usqp=CAU)

[Lien test W et X](https://calculis.net/images/exemple-produit-de-matrices.png)