# Algorithme du pivot de Gauss

In [109]:
import numpy as np

## Préambule : permutation de lignes

In [110]:
def permute(M: list, L1: int, L2: int) -> list:
    M3 = np.copy(M)
    M3[L1] = M[L2]
    M3[L2] = M[L1]
    return M3

In [111]:
M = np.array([[1,1,2,-1],[1,0,-1,2],[2,1,3,2],[-1,-2,0,4]])
M

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

In [112]:
permute(M,2,3)

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [-1, -2,  0,  4],
       [ 2,  1,  3,  2]])

## 1. Matrice échelonnée triangulaire

### 1.1 Exercice : recherche du pivot

In [214]:
def recherchepivot(M: list, j: int) -> list:
    M1 = np.copy(M)
    a = M1
    if M1[j, j] == 0:
        a = permute(M1, j, j+1)
    return a

In [215]:
M

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

In [216]:
recherchepivot(M,1)

array([[ 1,  1,  2, -1],
       [ 2,  1,  3,  2],
       [ 1,  0, -1,  2],
       [-1, -2,  0,  4]])

In [217]:
recherchepivot(M,0)

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

### 1.2 Exercice : annulation des coefficients

In [194]:
def annulcoeff(M: list, j: int) -> list:
    M1 = recherchepivot(M, j)
    for i in range(j+1, np.shape(M1)[0]):
        M1[:][i]=M1[:][i]*M1[j][j]-M1[i][j]*M1[:][j]
    return M1

In [195]:
M = np.array([[1,1,2,-1],[1,0,-1,2],[2,1,3,2],[-1,-2,0,4]])
M
annulcoeff(M,1)

array([[ 1,  1,  2, -1],
       [ 2,  1,  3,  2],
       [ 1,  0, -1,  2],
       [ 3,  0,  6,  8]])

### 1.3 Exercice : pivot de Gauss

In [218]:
def gauss(M: list) -> list:
    M1 = np.copy(M)
    for i in range(np.shape(M1)[0]):
        M1 = annulcoeff(M1, i)
    return M1

In [219]:
M = np.array([[1,1,2,-1],[1,0,-1,2],[2,1,3,2],[-1,-2,0,4]])
M

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

In [221]:
M2 = gauss(M)
M2

array([[ 1,  1,  2, -1],
       [ 0, -1, -3,  3],
       [ 0,  0, -2, -1],
       [ 0,  0,  0, -5]])

## 2. Matrice échelonnée diagonale

### 2.1 Exercice : remontée de l'algorithme de Gauss

In [222]:
def remonte(G: list) -> list:
    G1 = np.copy(G)
    for i in range(np.shape(G1)[0]-2, -1, -1):
        for j in range(np.shape(G1)[0]-1, i, -1):
            G1[i][:]=G1[:][i]*G1[j][j]-G1[i][j]*G1[:][j]
    return G1

In [224]:
remonte(M2)

array([[-2500,     0,     0,     0],
       [    0,    50,     0,     0],
       [    0,     0,    10,     0],
       [    0,     0,     0,    -5]])

In [225]:
def diagonale(M: list) -> list:
    M1 = gauss(M)
    M1 = remonte(M1)
    return M1

In [226]:
M = np.array([[1,1,2,-1],[1,0,-1,2],[2,1,3,2],[-1,-2,0,4]])
M

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

In [227]:
diagonale(M)

array([[-2500,     0,     0,     0],
       [    0,    50,     0,     0],
       [    0,     0,    10,     0],
       [    0,     0,     0,    -5]])

### 2.2 Bonus : inversion d'une matrice

In [228]:
def inverse(M: list) -> list:
    M1 = np.linalg.inv(M)
    M1 = np.round(M1, 1)
    return M1

In [229]:
M = np.array([[1,1,2,-1],[1,0,-1,2],[2,1,3,2],[-1,-2,0,4]])
M

array([[ 1,  1,  2, -1],
       [ 1,  0, -1,  2],
       [ 2,  1,  3,  2],
       [-1, -2,  0,  4]])

In [230]:
inverse(M)

array([[ 4. ,  2. , -2. ,  1. ],
       [-5.6, -2.2,  3. , -1.8],
       [ 0.4, -0.2,  0. ,  0.2],
       [-1.8, -0.6,  1. , -0.4]])